### ISSUE TITLE
lint error line number off-by-one

### ISSUE THREAD

**Issue by helinwang** [favadi/flycheck-gometalinter#11]
Appreciate the repo! Very helpful.

I have one quesiton, when using it, the underline changed to "aboveline":

<img width="296" alt="screen shot 2017-05-26 at 1 52 44 pm" src="https://cloud.githubusercontent.com/assets/1724178/26512260/a2e55e56-421a-11e7-9b34-190cc26ab2b8.png">

As shown in the picture, I think the red line show be below the code, not above the code. Any idea how to fix it?

My configuration is in this repo: https://github.com/helinwang/go-emacs/

Thanks!

**Comment by jackbearheart** [comment]
I see this too.

Looks like for the checkstyle output from gometalinter, gometalinter indicates "column 0", but with the correct line number, and then flycheck interprets this to be the previous line. As a temporary workaround I added
```
		col := 1
		if issue.Col > 0 {
			col = issue.Col
		}
```
to my gometalinter checkstyle.go... this is still very ugly.

I haven't gone further into this. Either 1) the gometalinter checkstyle output from certain linters needs to be improved so that it sets the column correctly or 2) the flycheck checkstyle parser needs to handle column=0 more nicely.

In either case, the bug is not really in flycheck-gometalinter, which is just an adapter from `gometalinter --checkstyle` to flycheck.

**Comment by helinwang** [comment]
Thanks for your input! Glad to know about what is really going on. I just got used to the problem :p
